### PR TITLE
4: Removed eval from render array.

### LINKED ISSUE #4: Eval blocked by Windows Defender
Unhandled exception at line 157, column 5 in json.asp
0x800a802d - Microsoft VBScript runtime error: This script contains malicious content and has been blocked by your antivirus software.: 'Eval' occurred

### PR DESCRIPTION
**Pull request by ronald-mz**
Resolves: #4 

~~Turns out, you can just pass an array to access a multi-dimensional array. Didn't know that until I tried it.~~

### CODE REVIEW

**Comment by tugrul** [comment]
Did you test this code? I did not remember a class has a function named `split`.

Eval is a hack to access multidimensional arrays' indices.

```vbscript
Dim multi(2,3,4)

multi(1,1,1) = "testing"

' it works
WScript.Echo eval("multi(1,1,1)")


' doesnt work
WScript.Echo multi("1,1,1".split(","))

' doesnt work
WScript.Echo multi(Array(1,1,1))

```

**Comment by ronald-mz** [comment]
Hrm. Two things there. One, it's supposed to be

```vbScript
multi(split("1,1,1", ","))
```

That doesn't work either though. I think the

```vbScript
on error resume 0
```

Was tricking me. That line makes it so that vbScript ignores all errors.

Either way, this may require some more tinkering to solve. getRows of a recordset returns a rectangular array rather than an array of arrays. And I'm sure some users will send in rectangular arrays.

Maybe a procedure that will convert a rectangular array into an array of arrays? That may be more overhead than we'd like though.

**Comment by tugrul** [comment]
> Maybe a procedure that will convert a rectangular array into an array of arrays? That may be more overhead than we'd like though.

Nothing change. You need to solve same problem in the procedure again. The problem is VBScript doesn't have functionality to iterate multi-dim arrays. We can't craft indices maps dynamically. 

Maybe the Windows Defender problem is obsolete and not necessary make changes. Because I did not encounter the problem while testing eval.

**Comment by ronald-mz** [comment]
> Nothing change. You need to solve same problem in the procedure again. The problem is VBScript doesn't have functionality to iterate multi-dim arrays. We can't craft indices maps dynamically.

I'd not thought of this. I guess I am too used to newer languages that make this easier. So there's likely nothing that can be done.

> Maybe the Windows Defender problem is obsolete and not necessary make changes. Because I did not encounter the problem while testing eval.

That may be true too. The reported issue was some two years ago and I've not seen the issue myself. I had assumed the user was under some sort of environment that prevented it.

Regardless, it sounds like there isn't anything we can do to fix the issue. So if you've no complaints, I will close this branch.

**Pull request closed without merging**
